/**
 * MaaS (Model-as-a-Service) open model definitions for Vertex AI
 * Source: https://cloud.google.com/vertex-ai/generative-ai/docs/partner-models/use-partner-models
 * Pricing: https://cloud.google.com/vertex-ai/generative-ai/pricing#partner-models
 * All prices per 1M tokens
 */

import type { VertexModelConfig } from "../types.js";

export const MAAS_MODELS: VertexModelConfig[] = [
  // --- Meta Llama ---
  {
    id: "llama-4-maverick",
    name: "Llama 4 Maverick",
    apiId: "meta/llama-4-maverick-17b-128e-instruct-maas",
    publisher: "meta",
    endpointType: "maas",
    contextWindow: 524288,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.35,
      output: 1.15,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "llama-4-scout",
    name: "Llama 4 Scout",
    apiId: "meta/llama-4-scout-17b-16e-instruct-maas",
    publisher: "meta",
    endpointType: "maas",
    contextWindow: 1310720,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.25,
      output: 0.7,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "llama-3.3-70b",
    name: "Llama 3.3 70B",
    apiId: "meta/llama-3.3-70b-instruct-maas",
    publisher: "meta",
    endpointType: "maas",
    contextWindow: 128000,
    maxTokens: 8192,
    input: ["text"],
    reasoning: false,
    tools: true,
    cost: {
      input: 0.72,
      output: 0.72,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },

  // --- Mistral AI ---
  {
    id: "mistral-medium-3",
    name: "Mistral Medium 3",
    apiId: "mistralai/mistral-medium-3",
    publisher: "mistralai",
    endpointType: "maas",
    contextWindow: 128000,
    maxTokens: 32000,
    input: ["text"],
    reasoning: false,
    tools: true,
    cost: {
      input: 0.4,
      output: 2.0,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "mistral-small-3.1",
    name: "Mistral Small 3.1",
    apiId: "mistralai/mistral-small-2503",
    publisher: "mistralai",
    endpointType: "maas",
    contextWindow: 128000,
    maxTokens: 32000,
    input: ["text"],
    reasoning: false,
    tools: true,
    cost: {
      input: 0.1,
      output: 0.3,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "codestral-2",
    name: "Codestral 2",
    apiId: "mistralai/codestral-2",
    publisher: "mistralai",
    endpointType: "maas",
    contextWindow: 256000,
    maxTokens: 32000,
    input: ["text"],
    reasoning: false,
    tools: true,
    cost: {
      input: 0.3,
      output: 0.9,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "mistral-ocr",
    name: "Mistral OCR",
    apiId: "mistralai/mistral-ocr-2505",
    publisher: "mistralai",
    endpointType: "maas",
    contextWindow: 128000,
    maxTokens: 32000,
    input: ["text", "image"],
    reasoning: false,
    tools: false,
    cost: {
      input: 0.0005,
      output: 0.0005,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },

  // --- DeepSeek ---
  {
    id: "deepseek-v3.2",
    name: "DeepSeek V3.2",
    apiId: "deepseek-ai/deepseek-v3.2-maas",
    publisher: "deepseek-ai",
    endpointType: "maas",
    contextWindow: 163840,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.56,
      output: 1.68,
      cacheRead: 0.056,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "deepseek-v3.1",
    name: "DeepSeek V3.1",
    apiId: "deepseek-ai/deepseek-v3.1-maas",
    publisher: "deepseek-ai",
    endpointType: "maas",
    contextWindow: 163840,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.6,
      output: 1.7,
      cacheRead: 0.06,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "deepseek-r1",
    name: "DeepSeek R1",
    apiId: "deepseek-ai/deepseek-r1-0528-maas",
    publisher: "deepseek-ai",
    endpointType: "maas",
    contextWindow: 163840,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 1.35,
      output: 5.4,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "deepseek-ocr",
    name: "DeepSeek OCR",
    apiId: "deepseek-ai/deepseek-ocr-maas",
    publisher: "deepseek-ai",
    endpointType: "maas",
    contextWindow: 163840,
    maxTokens: 32000,
    input: ["text", "image"],
    reasoning: false,
    tools: false,
    cost: {
      input: 0.3,
      output: 1.2,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },

  // --- OpenAI (gpt-oss) ---
  {
    id: "gpt-oss-120b",
    name: "GPT-OSS 120B",
    apiId: "openai/gpt-oss-120b-maas",
    publisher: "openai",
    endpointType: "maas",
    contextWindow: 131072,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.09,
      output: 0.36,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "gpt-oss-20b",
    name: "GPT-OSS 20B",
    apiId: "openai/gpt-oss-20b-maas",
    publisher: "openai",
    endpointType: "maas",
    contextWindow: 131072,
    maxTokens: 32000,
    input: ["text"],
    reasoning: false,
    tools: true,
    cost: {
      input: 0.07,
      output: 0.25,
      cacheRead: 0.007,
      cacheWrite: 0,
    },
    region: "global",
  },

  // --- Qwen ---
  {
    id: "qwen3-235b",
    name: "Qwen 3 235B",
    apiId: "qwen/qwen3-235b-a22b-instruct-2507-maas",
    publisher: "qwen",
    endpointType: "maas",
    contextWindow: 262144,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.22,
      output: 0.88,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "qwen3-next-instruct",
    name: "Qwen 3 Next Instruct",
    apiId: "qwen/qwen3-next-instruct-80b-maas",
    publisher: "qwen",
    endpointType: "maas",
    contextWindow: 262144,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.15,
      output: 1.2,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "qwen3-next-thinking",
    name: "Qwen 3 Next Thinking",
    apiId: "qwen/qwen3-next-thinking-80b-maas",
    publisher: "qwen",
    endpointType: "maas",
    contextWindow: 262144,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.15,
      output: 1.2,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "qwen3-coder",
    name: "Qwen 3 Coder",
    apiId: "qwen/qwen3-coder-480b-a35b-instruct-maas",
    publisher: "qwen",
    endpointType: "maas",
    contextWindow: 262144,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.22,
      output: 1.8,
      cacheRead: 0.022,
      cacheWrite: 0,
    },
    region: "global",
  },

  // --- Moonshot ---
  {
    id: "kimi-k2-thinking",
    name: "Kimi K2 Thinking",
    apiId: "moonshotai/kimi-k2-thinking-maas",
    publisher: "moonshotai",
    endpointType: "maas",
    contextWindow: 262144,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.6,
      output: 2.5,
      cacheRead: 0.06,
      cacheWrite: 0,
    },
    region: "global",
  },

  // --- MiniMax ---
  {
    id: "minimax-m2",
    name: "MiniMax M2",
    apiId: "minimaxai/minimax-m2-maas",
    publisher: "minimaxai",
    endpointType: "maas",
    contextWindow: 196608,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.3,
      output: 1.2,
      cacheRead: 0.03,
      cacheWrite: 0,
    },
    region: "global",
  },

  // --- GLM (Zhipu AI) ---
  {
    id: "glm-5",
    name: "GLM 5",
    apiId: "zai-org/glm-5-maas",
    publisher: "zai-org",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 1.0,
      output: 3.2,
      cacheRead: 0.1,
      cacheWrite: 0,
    },
    region: "global",
  },
  {
    id: "glm-4.7",
    name: "GLM 4.7",
    apiId: "zai-org/glm-4.7-maas",
    publisher: "zai-org",
    endpointType: "maas",
    contextWindow: 200000,
    maxTokens: 32000,
    input: ["text"],
    reasoning: true,
    tools: true,
    cost: {
      input: 0.6,
      output: 2.2,
      cacheRead: 0,
      cacheWrite: 0,
    },
    region: "global",
  },
];
